from google.adk.agents import Agent

def create_educational_story(topic: str, lesson: str) -> str:
    story_prompt = (
        f"Craft a compelling and creative short story about '{topic}' "
        f"that powerfully teaches the following lesson: '{lesson}'. "
        f"Ensure the story has a clear beginning, rising action, climax, and resolution "
        f"that reinforces the lesson. Make it engaging for a general audience."
    )

    return (
        f"Here is a story outline generated for your lesson:\n\n"
        f"**Topic:** {topic}\n"
        f"**Lesson to Convey:** {lesson}\n\n"
        f"**Story Prompt given to AI:**\n"
        f"> {story_prompt}\n\n"
        f"*(The actual story content would be generated by the AI based on the above prompt when this tool is invoked by the agent.)*"
    )

story_teacher_agent = Agent(
    name="story_teacher_agent",
    model="gemini-1.5-flash-latest",
    instruction="When a teacher provides a topic and a key lesson, generate a creative and engaging story that effectively teaches that lesson.",
    tools=[create_educational_story],
)